config/routes.rb
Rails.application.routes.draw do
  get "users/show"
  get "games/index", as: "games"
  get "games/show"
  get "games/edit"
  get "games/new"
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root "gameup#show", as: :authenticated_root
    end

    unauthenticated do
      root "gameup#index", as: :unauthenticated_root
    end
  end

  resources :users, only: [:show]
  get "/search", to: "gameup#search"
  post "/search", to: "gameup#create"
  post "/", to: "gameup#create"
  get "gameup/index"
  get "gameup/show"
  resources :games
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
end

app/models/gameup.rb
class Gameup
  require "igdb_client"

  # initialize with api_key
  IGDB::API.api_key = ENV["IGDB_API_KEY"]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :games
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  respond_to :html, :json

  def index
    @games = Game.all
  end

  def show
    @game = Game.find_by(id: params[:id])
  end

  def edit
    @game = Game.find_by(id: params[:id])
  end

  def update
    @game = Game.find_by(id: params[:id])
    @game.update(game_params)
    respond_with @game
  end

  def new
    @game = Game.new
  end

  def create
    game = current_user.games.create(game_params)
    redirect_to user_path(current_user.id)
  end

  def destroy
    game = Game.find_by(id: params[:id])
    game.destroy
    redirect_to user_path(current_user.id)
  end

  private

  def game_params
    params.require(:game).permit(:name, :cover, :release_date, :user_id, :category)
  end
end

app/controllers/gameup_controller.rb
class GameupController < ApplicationController
  def index
    # initialize with api_key
    client = IGDB::Client.new ENV["IGDB_API_KEY"]
    @results = client.games 1942, {fields: "name"}
  end

  def show
    @games = Game.all
  end

  def search
    client = IGDB::Client.new ENV["IGDB_API_KEY"]

    @term = params[:term]
    @result = client.search_games @term, {fields: "name,release_dates,esrb.synopsis,rating,cover"}
    @game = Game.new
  end

  def create
    game = current_user.games.create(game_params)
  end

  private

  def game_params
    params.permit(:name, :cover, :release_date, :user_id, :category)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :json

  def show
    @user = User.find_by(id: params[:id])
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    user = User.find_by(id: params[:id])
    user.update(user_params)
    respond_with user
  end

  private

  def game_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/gameup_helper.rb
module GameupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_form.html.erb
<%= form_for @game do |f| %> 

<%= f.select :category, options_for_select([['Currently Playing', "current"], ['Want To Play', "to_play"],  ['Finished', "finished"]], selected: @game.category || nil),
         include_blank: false, class:'form-control m-b'%>

<%= f.submit %>

<% end %>

app/views/games/index.html.erb
<h2>index</h2>
<% @games.each do |game| %>
<%= game.name %>
<% end %>

app/views/games/new.html.erb
<h2>new</h2>

app/views/games/show.html.erb
<h1>Games#show</h1>
<p>Find me in app/views/games/show.html.erb</p>

app/views/gameup/_form.html.erb
<%= form_for games_new_path(@game), method: :post do |f| %>
  <%= hidden_field_tag :name, @game_name  %>
  <%= hidden_field_tag :cover, @game_cover %>
  <%= hidden_field_tag :release_date, @game_date %>
  <%= hidden_field_tag :category, "current" %>
  <%= f.submit 'Add Game', class: 'formButton' %>
<% end %>

app/views/gameup/index.html.erb
<h2 class="homepage-p">Create a profile and start keeping records of your games!</h2>
<div class="home-img-div">
<%= image_tag('presstar3.gif', class: 'home-img') %>
</div>
<div class="homepage-div">
<span><%= link_to 'Log In', new_user_session_path %></span>
<span><%= link_to "Sign Up", new_user_registration_path %></span>
</div>

app/views/gameup/search.html.erb
<div class="centered">
  <h3>Search results for <%= @term %></h3>
</div>
<div class="container">

  <% if @result.empty? %>
    <p>No match found</p>
  <% else %>
       

    <% @result.each do |game| %>
       <% @game_name = game.name  %>
       <% if game.release_dates %>
        <% @game_date =  game.release_dates[0].y %>
        <% end %>
        <div class="card">
        <% if game.cover %>
        <% @game_cover = game.cover.url %>
       <img src="<%=game.cover.url%>" alt="">      
        <% end  %>

<% if user_signed_in? %>
<div class="popup">
  <div class="popUp-content">
            <div class="popUp_Border">
                            <span class="close">&times;</span>
                            <p>Game Added!</p>
        </div>
</div>
</div>
        <p class="add-btn"><%= render partial: 'form' %></p>
<% end %>

       <p class="title clear-fix"><%=  game.name  %> </p>
        <% if game.release_dates %>
       <p class="clear-fix">Released: <%=  game.release_dates[0].y  %> </p>
        <% end  %>
        </div>
    <% end %>

  <% end %>
</div>
<script>
    console.log('Test1');

  $('.formButton').click( function () {
    console.log('Test2');
       $('.popup').css('display',"block");
    });
  $('.close').click( function () {
       $('.popup').css('display',"none");
    });
 </script> 

app/views/gameup/show.html.erb
<h2 class="centralized">Recently Added by the Community</h2>
<hr>

<% @games.reverse.each do |game| %>
<%@game_name  = game.name %>
<%@game_cover = game.cover %>
  <% @game_date =  game.release_date %>
        <div class="card">
       
       <img src="<%=game.cover%>" alt="">      
<% if user_signed_in? %>
<div class="popup">
  <div class="popUp-content">
            <div class="popUp_Border">
                            <span class="close">&times;</span>
                            <p>Game Added!</p>
        </div>
</div>
</div>
        <p class="add-btn"><%= render partial: 'form' %></p>
<% end %>
       <p class="title clear-fix"><%= game.name %> </p>
       <p class="clear-fix">Released: <%=  game.release_date %> </p>
       
        </div>
    <% end %>

  <script>
  $('.formButton').click( function () {
       $('.popup').css('display',"block");
    });
  $('.close').click( function () {
       $('.popup').css('display',"none");
    });
 </script> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://fonts.googleapis.com/css?family=Press+Start+2P|VT323" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav>
  <% if user_signed_in? %>
  <span><%= link_to 'Home', "/gameup/show" %></span>
  <span><%= link_to 'Profile', "/users/#{current_user.id}" %></span>
<span><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></span>
  <% else %>
  <span><%= link_to 'Log In', new_user_session_path %></span>
<span><%= link_to "Sign Up", new_user_registration_path %></span>
<% end %>
<span class="right-most"><%= form_tag '/search', method: :get do %>
        <%= text_field_tag :term, params[:term], placeholder: '   Search games', class: "search-field" %>
      <% end %> </span>

  </nav>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %> 

<%= f.text_field :username %>

<%= f.submit %>

<% end %>

app/views/users/edit.html.erb
<%= render partial: 'form' %>

app/views/users/show.html.erb
<div class="clear-fix profile-header">
<%= image_tag('header2.gif', style: "height: 40vh; width: 100vw; background-size: contain;", class: 'profile-img') %>
<h2 class="clear-fix username">@<%= @user.username %></h2>
</div>

<div>

<h3 class="cat-name">Currently Playing</h3>

<% @user.games.each do |g|%>

<% if g.category == "current" %>

<div class="game">

<img src="<%= g.cover %>" alt="">
<p><%= best_in_place g, :category, :as => :select, :collection => [['finished', 'Finished'], ['to_play', 'Want to Play'], ['current', 'Currently Playing']] %></p>

<p><%= link_to 'Remove', "/games/#{g.id}", method: "delete" %> <p>

<% end %>

</div>

<% end %>

</div>

<hr class="clear-fix">

<div>

<h3 class="cat-name">Finished</h3>

<% @user.games.each do |g|%>

<% if g.category == "finished" %>

<div class="game">

<img src="<%= g.cover %>" alt="">
<p><%= best_in_place g, :category, :as => :select, :collection => [['finished', 'Finished'], ['to_play', 'Want to Play'], ['current', 'Currently Playing']] %></p>


<p><%= link_to 'Remove', "/games/#{g.id}", method: "delete" %> <p>

<% end %>

</div>

<% end %>

</div>

<hr class="clear-fix">

<div>

<h3 class="cat-name">Want To Play</h3>

<% @user.games.each do |g|%>

<% if g.category == "to_play" %>

<div class="game">

<img src="<%= g.cover %>" alt="">
<p><%= best_in_place g, :category, :as => :select, :collection => [['finished', 'Finished'], ['to_play', 'Want to Play'], ['current', 'Currently Playing']] %></p>


<p><%= link_to 'Remove', "/games/#{g.id}", method: "delete" %> <p>

<% end %>

</div>

<% end %>

</div>

<hr class="clear-fix">